apiVersion: batch/v1
kind: Job
metadata:
  name: migrations-job
spec:
  template:
    spec:
      containers:
        - name: migrations-container
          image: dosxana/migrations:latest
          envFrom:
            - secretRef:
                name: env-secret
          command: ["sh", "-c", "alembic upgrade head"]
      restartPolicy: OnFailure
