global:
  resolve_timeout: 5m

receivers:
  - name: email-receiver
    email_configs:
      - to: "${ALERT_EMAIL_TO}"
        from: "${ALERT_EMAIL_FROM}"
        smarthost: "${ALERT_EMAIL_SMARTHOST}"
        auth_username: "${ALERT_EMAIL_USERNAME}"
        auth_password: "${ALERT_EMAIL_PASSWORD}"

  - name: telegram-receiver
    webhook_configs:
      - url: "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage?chat_id=${TELEGRAM_CHAT_ID}"

route:
  group_by: [ 'alertname' ]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: email-receiver
  routes:
    - match:
        severity: critical
      receiver: telegram-receiver
